import type { AIPanelPlugin } from "./types";

export const initialPlugins: AIPanelPlugin[] = [
  // Hosting & Operations
  {
    id: "hosting-core",
    name: "Hosting Operations",
    description: "Manage hosting plans, resource quotas, client subscriptions, bandwidth, and automated provisioning.",
    version: "1.2.0",
    author: "AIPanel Core Team",
    category: "hosting",
    installed: true,
    enabled: true,
    compatibleVersion: ">=0.1.0",
    routeId: "hosting",
    sidebarLabel: "Hosting Plans",
    sidebarSection: "hosting",
    permissions: [
      { id: "manage_plans", name: "Manage Plans", description: "Create and modify hosting packages and pricing tiers" },
      { id: "quota_enforcement", name: "Enforce Quotas", description: "Limit CPU, disk, and bandwidth usage per client" },
    ],
  },
  {
    id: "client-crm",
    name: "Client CRM & Invoicing",
    description: "Lightweight CRM built specifically for hosting and development operations. Track clients, renewals, tickets, and revenue.",
    version: "1.0.4",
    author: "AIPanel Core Team",
    category: "hosting",
    installed: true,
    enabled: true,
    compatibleVersion: ">=0.1.0",
    routeId: "clients",
    sidebarLabel: "Clients & CRM",
    sidebarSection: "hosting",
    permissions: [
      { id: "read_clients", name: "Read Client Data", description: "View client profiles, domains, and associated websites" },
      { id: "billing_manage", name: "Invoicing & Billing", description: "Track invoices and renewal schedules" },
    ],
  },
  {
    id: "domains-dns",
    name: "Domain Management & Expiry",
    description: "Centralized domain inventory, automated 90/60/30/14/7/3/1 day expiry notification cascades, DNS records, and SSL tracking.",
    version: "2.1.0",
    author: "AIPanel Core Team",
    category: "hosting",
    installed: true,
    enabled: true,
    compatibleVersion: ">=0.1.0",
    routeId: "domains",
    sidebarLabel: "Domains & SSL",
    sidebarSection: "infrastructure",
    permissions: [
      { id: "manage_dns", name: "Manage DNS Records", description: "Create, update, and delete DNS A/AAAA/CNAME records" },
      { id: "ssl_renew", name: "SSL Certificate Renewal", description: "Request and renew Let's Encrypt certificates" },
    ],
  },
  {
    id: "email-suite",
    name: "Email Management",
    description: "Orchestrate mailboxes, aliases, forwarding, SPF, DKIM, DMARC with Mailcow or Postfix/Dovecot.",
    version: "0.9.5",
    author: "AIPanel Core Team",
    category: "hosting",
    installed: false,
    enabled: false,
    compatibleVersion: ">=0.1.0",
    routeId: "email",
    sidebarLabel: "Email Accounts",
    sidebarSection: "hosting",
    permissions: [
      { id: "mail_accounts", name: "Manage Mailboxes", description: "Provision and revoke email addresses and mail quotas" },
      { id: "dns_email", name: "DNS Records", description: "Verify and write MX, SPF, DKIM records" },
    ],
  },

  // Infrastructure & Cloud
  {
    id: "cloudflare-tools",
    name: "Cloudflare Integration",
    description: "Automated Zero Trust tunnels, Cloudflare DNS synchronization, and edge caching controls.",
    version: "1.4.1",
    author: "Cloudflare / AIPanel",
    category: "infrastructure",
    installed: true,
    enabled: true,
    compatibleVersion: ">=0.1.0",
    permissions: [
      { id: "read_dns", name: "Read DNS", description: "Query zone information and active records" },
      { id: "manage_tunnels", name: "Manage Tunnels", description: "Create and bind cloudflared outbound connections" },
    ],
  },
  {
    id: "docker-engine",
    name: "Docker Container Manager",
    description: "Full Docker SDK integration for managing containers, images, volumes, bridge networks, and Compose stacks.",
    version: "2.0.0",
    author: "AIPanel Core Team",
    category: "infrastructure",
    installed: true,
    enabled: true,
    compatibleVersion: ">=0.1.0",
    permissions: [
      { id: "docker_socket", name: "Docker Socket Access", description: "Direct communication with local /var/run/docker.sock" },
      { id: "container_exec", name: "Container Exec", description: "Spawn processes inside running containers" },
    ],
  },
  {
    id: "backup-s3",
    name: "Cloudflare R2 & S3 Backups",
    description: "Encrypted automated snapshot shipping to Amazon S3, Cloudflare R2, or Backblaze B2 with retention rules.",
    version: "1.1.2",
    author: "AIPanel Core Team",
    category: "backup",
    installed: true,
    enabled: true,
    compatibleVersion: ">=0.1.0",
    permissions: [
      { id: "storage_write", name: "Object Storage Write", description: "Upload encrypted database and file archives" },
    ],
  },

  // AI Providers
  {
    id: "ai-gemini",
    name: "Google Gemini Provider",
    description: "Connect Google Gemini 2.5 & 3.0 models for automated coding, security scans, and infrastructure reasoning.",
    version: "1.3.0",
    author: "AIPanel AI",
    category: "ai",
    installed: true,
    enabled: true,
    compatibleVersion: ">=0.1.0",
    permissions: [
      { id: "ai_inference", name: "Model Inference", description: "Send prompts and code snippets to Gemini API" },
    ],
  },
  {
    id: "ai-ollama",
    name: "Ollama Local AI Provider",
    description: "100% private, offline, air-gapped local AI coding using DeepSeek Coder, Llama 3, or Qwen running on your hardware.",
    version: "1.0.0",
    author: "Community",
    category: "ai",
    installed: true,
    enabled: true,
    compatibleVersion: ">=0.1.0",
    permissions: [
      { id: "local_http", name: "Localhost HTTP", description: "Connect to http://localhost:11434" },
    ],
  },
  {
    id: "ai-openai",
    name: "OpenAI & Anthropic Suite",
    description: "Bring your own API keys for GPT-4o, Claude 3.7 Sonnet, and OpenAI-compatible endpoints with token budgets.",
    version: "1.2.0",
    author: "AIPanel AI",
    category: "ai",
    installed: true,
    enabled: true,
    compatibleVersion: ">=0.1.0",
    permissions: [
      { id: "ai_inference", name: "Model Inference", description: "Send code and commands to OpenAI & Anthropic endpoints" },
    ],
  },

  // Monitoring
  {
    id: "monitoring-alerts",
    name: "Incident & Webhook Alerts",
    description: "Multi-channel alerting via Discord, Slack, Telegram, Webhook, and Email for high CPU, SSL expiry, and container crashes.",
    version: "1.0.2",
    author: "AIPanel Core Team",
    category: "monitoring",
    installed: true,
    enabled: true,
    compatibleVersion: ">=0.1.0",
    permissions: [
      { id: "network_out", name: "Outbound Webhooks", description: "Deliver payload events to configured webhook endpoints" },
    ],
  },
];
